// flow-typed signature: 9cf1a087838c0ea1b1a8953a1aedf09c
// flow-typed version: <<STUB>>/@svgr/webpack_v4.3.3/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/webpack/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/webpack/lib/index' {
  declare module.exports: $Exports<'@svgr/webpack/lib'>;
}
declare module '@svgr/webpack/lib/index.js' {
  declare module.exports: $Exports<'@svgr/webpack/lib'>;
}
