// flow-typed signature: 0f40a25a63d8375ea249ebd920e09d23
// flow-typed version: <<STUB>>/bson-objectid_v^1.3.0/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bson-objectid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bson-objectid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bson-objectid/objectid' {
  declare module.exports: any;
}

declare module 'bson-objectid/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bson-objectid/objectid.js' {
  declare module.exports: $Exports<'bson-objectid/objectid'>;
}
declare module 'bson-objectid/test/test.js' {
  declare module.exports: $Exports<'bson-objectid/test/test'>;
}
