export const clientConstants = {
  SET_GUEST_USER: "SET_GUEST_USER"
};

export const conversationConstants = {
  CONVERSATION_REQUEST: "CONVERSATION_REQUEST",
  CONVERSATION_SUCCESS: "CONVERSATION_SUCCESS",
  CONVERSATION_ERROR: "CONVERSATION_ERROR",
  OPEN_CONVERASTION: "OPEN_CONVERSATION", 
  CLOSE_CONVERSATION: "CLOSE_CONVERSATION",
  DELETE_CONVERSATION: "DELETE_CONVERSATION", 
};

export const messageConstants = {
  MESSAGE_REQUEST: "MESSAGE_REQUEST",
  MESSAGE_ERROR: "MESSAGE_ERROR",
  MESSAGE_SUCCESS: "MESSAGE_SUCCESS",
  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  MARK_READ: "MARK_READ"
};


