export const conversationConstants = {
  CONVERSATION_REQUEST: "CONVERSATION_REQUEST",
  CONVERSATION_ERROR: "CONVERSATION_ERROR",
  OPEN_CONVERASTION: "OPEN_CONVERSATION", 
  CLOSE_CONVERSATION: "CLOSE_CONVERSATION",
  DELETE_CONVERSATION: "DELETE_CONVERSATION",
  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  MARK_READ: "MARK_READ"
};

