export const clientConstants = {
  SET_GUEST_USER: "SET_GUEST_USER",
  SET_ADMIN: "SET_ADMIN",
  LOG_OUT_ADMIN: "LOG_OUT_ADMIN",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_ERROR: "LOGIN_ERROR"
};

export const conversationConstants = {
  CONVERSATION_REQUEST: "CONVERSATION_REQUEST",
  CONVERSATION_SUCCESS: "CONVERSATION_SUCCESS",
  CONVERSATION_ERROR: "CONVERSATION_ERROR",
  OPEN_CONVERASTION: "OPEN_CONVERSATION", 
  CLOSE_CONVERSATION: "CLOSE_CONVERSATION",
  UPDATE_CONVERSATION: "UPDATE_CONVERSATION",
  DELETE_CONVERSATION: "DELETE_CONVERSATION",
};

export const messageConstants = {
  MESSAGE_REQUEST: "MESSAGE_REQUEST",
  MESSAGE_ERROR: "MESSAGE_ERROR",
  MESSAGE_SUCCESS: "MESSAGE_SUCCESS",
  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  MARK_READ: "MARK_READ"
};

export const roomConstants = {
  ROOM_REQUEST: "ROOM_REQUEST",
  ROOM_CREATED: "ROOM_CREATED",
  ROOM_UPDATED: "ROOM_UPDATED",
  ROOM_DELETED: "ROOM_DELETED",
  ROOM_ERROR: "ROOM_ERROR",
  ROOM_IMG_REQUEST: "ROOM_IMG_REQUEST",
  ROOM_IMG_UPLOADED: "ROOM_IMG_UPLOADED",
  ROOM_IMG_DELETED: "ROOM_IMG_DELETED",
  ROOM_IMG_ERROR: "ROOM_IMG_ERROR",
  ADD_NEW_ROOM: "ADD_ROOM_TO_STATE",
  OPEN_ROOM: "OPEN_ROOM",
  CLOSE_ROOM: "CLOSE_ROOM",
  SET_ROOMS: "SET_ROOMS"
};


